### ISSUE TITLE
Replace author TODOs

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/ScPCA-manuscript#104]
It seems we still have some `TODO` values in the author metadata. This issue tracks replacing those values.

https://github.com/AlexsLemonade/ScPCA-manuscript/blob/8558b4ff6642aea1bc281adf72273b014a0aae57/content/metadata.yaml#L76-L77

https://github.com/AlexsLemonade/ScPCA-manuscript/blob/8558b4ff6642aea1bc281adf72273b014a0aae57/content/metadata.yaml#L120

https://github.com/AlexsLemonade/ScPCA-manuscript/blob/8558b4ff6642aea1bc281adf72273b014a0aae57/content/metadata.yaml#L136

**Comment by jaclyn-taroni** [comment]
David: 0000-0003-1679-0353
